#if !canImport(ObjectiveC)
    import XCTest

    extension EncoderTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__EncoderTests = [
            ("testEncode", testEncode),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(EncoderTests.__allTests__EncoderTests),
        ]
    }
#endif
